### ISSUE TITLE
conf: Jenkins와 Docker를 사용하여 CI/CD 구축

### ISSUE THREAD

**Issue by WONSEOKJE** [Field-Passer/newFieldPasser-BE#11]
## Description(설명)

Jenkins와 Docker를 사용하여 CI/CD 구축

Jenkins 서버와 운영 서버를 따로 두어 구축

Github Webhook을 통해 레포에 push이벤트가 발생 시
1. Jenkins 서버에서 Github clone
2. clean build
3. Docker 이미지를 생성
4. Docker Hub에 이미지를 push
5. 운영 서버에서 Docker Hub의 이미지를 pull
6. Docker 실행

* properties 파일은 운영서버 /home/ubuntu/resources에 저장해놓고 Docker 실행시 해당 폴더를 /config에 마운트 시킴

## Tasks(New feature)

- [ ] Jenkins Server에 Docker 설치
- [ ] Jenkins Server에 Docker를 이용하여 Jenkins 실행
- [ ] Jenkins 접속
- [ ] Jenkins와 Github 연동
- [ ] Jenkins와 Docker Hub 연결
- [ ] Jenkins Server와 Spring Boot Server SSH 연결 설정
- [ ] Jenkins와 Slack 연동
- [ ] Jenkins Pipeline 구성

## References

https://velog.io/@wawakdev/DockerJenkins-CICD-%EC%9D%B4%EA%B1%B0%EB%B3%B4%EA%B3%A0-%EC%84%B1%EA%B3%B5%ED%95%98%EC%84%B8%EC%9A%94
